# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 00:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='value',
            field=models.CharField(max_length=256, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
