# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0002_auto_20161022_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=b''),
        ),
    ]
