# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 19:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import sanitizer.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0002_auto_20161107_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='value',
            field=sanitizer.models.SanitizedCharField(max_length=256, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.'), django.core.validators.MinLengthValidator(3, message='Field value must be at least 3 characters long')]),
        ),
    ]
